core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,

)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),

    path('order_summary/', OrderSummaryView.as_view(), name='order_summary'),

    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>', PaymentView.as_view(), name='payment'),

]

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('B', 'Beer'),
    ('W', 'Wine'),
    ('L', 'Liquor'),
    ('W', 'Whiskey')

)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)
CATEGORY_TYPES = (
    ('N', 'New'),
    ('B', 'Best Seller'),
    ('NY', 'NY Local'),
    ('S', 'Staff Pick'),
    ('P', 'Most Popular'),
    ('BL', '')
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    types = models.CharField(choices=CATEGORY_TYPES, max_length=2, null=True)

    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })



class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    city = models.CharField(max_length=100)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
<title>{% block head_title %}
    {% endblock %}</title>

    {% block extra_body %}
    {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
  </style>
</head>

{% include "navbar.html" %}

<body>

  <div class="mt-5 pt-4">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endif %}
  </div>

  {% block content %}
  {% endblock content %}

  {% include "footer.html" %}
  {% include "scripts.html" %}
</body>

</html>


    
    
 

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

grey lighten-3

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">
{#              <form>#}
{#                  {%  csrf_token %}#}
{#                  {{ form|crispy }}#}
{#                  <button class="btn btn-primary" type="submit">Checkout</button>#}
{#              </form>#}

            <!--Card content-->
            <form method="post" class="card-body">
            {% csrf_token %}

              <!--Grid row-->
{#              <div class="row">#}

                <!--Grid column-->
{#                <div class="col-md-6 mb-2">#}

{#                  <!--firstName-->#}
{#                  <div class="md-form ">#}
{#                    <input type="text" id="firstName" class="form-control">#}
{#                    <label for="firstName" class="">First name</label>#}
{#                  </div>#}

{#                </div>#}
                <!--Grid column-->

                <!--Grid column-->
{#                <div class="col-md-6 mb-2">#}
{##}
{#                  <!--lastName-->#}
{#                  <div class="md-form">#}
{#                    <input type="text" id="lastName" class="form-control">#}
{#                    <label for="lastName" class="">Last name</label>#}
{#                  </div>#}

{#                </div>#}
                <!--Grid column-->

{#              </div>#}
              <!--Grid row-->

{#              <!--Username-->#}
{#              <div class="md-form input-group pl-0 mb-5">#}
{#                <div class="input-group-prepend">#}
{#                  <span class="input-group-text" id="basic-addon1">@</span>#}
{#                </div>#}
{#                <input type="text" class="form-control py-0" placeholder="Username" aria-describedby="basic-addon1">#}
{#              </div>#}
{##}
{#              <!--email-->#}
{#              <div class="md-form mb-5">#}
{#                <input type="text" id="email" class="form-control" placeholder="youremail@example.com">#}
{#                <label for="email" class="">Email (optional)</label>#}
{#              </div>#}

              <!--address-->
              <div class="md-form mb-5">
{#                <input type="text" id="address" class="form-control" placeholder="1234 Main St">#}
                  {{ form.street_address }}
                <label for="address" class="">Address</label>
              </div>

              <!--address-2-->
              <div class="md-form mb-5">
{#                <input type="text" id="address-2" class="form-control" placeholder="Apartment or suite">#}
                  {{ form.apartment_address }}
                <label for="address-2" class="">Address 2 (optional)</label>
              </div>

              <!--Grid row-->
{#              <div class="row">#}

                <!--Grid column-->
{#                <div class="col-lg-4 col-md-12 mb-4">#}
{##}
{#                  <label for="country">Country</label>#}
{#                    {{ form.country }}#}
{#                  <select class="custom-select d-block w-100" id="country" required>#}
{#                    <option value="">Choose...</option>#}
{#                    <option>United States</option>#}
{#                  </select>#}
{#                  <div class="invalid-feedback">#}
{#                    Please select a valid country.#}
{#                  </div>#}

{#                </div>#}
                <!--Grid column-->

                <!--Grid column-->
{#                <div class="col-lg-4 col-md-6 mb-4">#}
{##}
{#                  <label for="state">City</label>#}
{#                    {{ form.city }}#}
{#                  <select class="custom-select d-block w-100" id="state" required>#}
{#                    <option value="">Choose...</option>#}
{#                    <option>New York City</option>#}
{#                  </select>#}
{#                  <div class="invalid-feedback">#}
{#                    Please provide a valid state.#}
{#                  </div>#}
{##}
{#                </div>#}
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip">Zip</label>
{#                  <input type="text" class="form-control" id="zip" placeholder="" required>#}
                    {{ form.zip }}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

{#              </div>#}
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
                <input{% if form.same_billing_address.value %} checked {% endif %} type="checkbox" class="custom-control-input" name="same_billing_address" id="same-address">
                  <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input {% if form.same_shipping_address.value %} checked {% endif %}type="checkbox" class="custom-control-input" id="save-info">
                  <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>

              <hr>

              <div class="d-block my-3">
                  {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{name}}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input"  required>
                  <label class="custom-control-label" for="{{name}}">{{name}}</label>
                </div>
                  {% endfor %}


              </div>
{#              <div class="row">#}
{#                <div class="col-md-6 mb-3">#}
{#                  <label for="cc-name">Name on card</label>#}
{#                  <input type="text" class="form-control" id="cc-name" placeholder="" required>#}
{#                  <small class="text-muted">Full name as displayed on card</small>#}
{#                  <div class="invalid-feedback">#}
{#                    Name on card is required#}
{#                  </div>#}
{#                </div>#}
{#                <div class="col-md-6 mb-3">#}
{#                  <label for="cc-number">Credit card number</label>#}
{#                  <input type="text" class="form-control" id="cc-number" placeholder="" required>#}
{#                  <div class="invalid-feedback">#}
{#                    Credit card number is required#}
{#                  </div>#}
{#                </div>#}
{#              </div>#}
{#              <div class="row">#}
{#                <div class="col-md-3 mb-3">#}
{#                  <label for="cc-expiration">Expiration</label>#}
{#                  <input type="text" class="form-control" id="cc-expiration" placeholder="" required>#}
{#                  <div class="invalid-feedback">#}
{#                    Expiration date required#}
{#                  </div>#}
{#                </div>#}
{#                <div class="col-md-3 mb-3">#}
{#                  <label for="cc-expiration">CVV</label>#}
{#                  <input type="text" class="form-control" id="cc-cvv" placeholder="" required>#}
{#                  <div class="invalid-feedback">#}
{#                    Security code required#}
{#                  </div>#}
{#                </div>#}
{#              </div>#}
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit" href="/payment/stripe">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->
<div class="col-md-12 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart #TODO</span>
            <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
                <small class="text-muted">{{ order_item.item.description}}</small>
              </div>
              <span class="text-muted">${{ order_item.get_final_price }}</span>
            </li>
            {% endfor %}
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>${{ order.get_total }}</strong>
            </li>
          </ul>
          <!-- Cart -->

        </div>
        <!--Grid column-->

      </div>

    </div>
        <!--Grid column-->
        <!--Grid column-->

      <!--Grid row-->

  </main>

{% endblock content %}

templates/home.html
{% extends "base.html" %}

{% block content %}


<main>
  <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Beer</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Wine</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Liquor</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Extras</a>
          </li>

        </ul>
        <!-- Links -->

        <form class="form-inline">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <div class="row wow fadeIn">

        {% for item in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">

          <div class="card">

            <div class="view overlay">
{#              <img src="https://products2.imgix.drizly.com/mi_7027.jpg" class="card-img-top" alt="">#}
                <img src="{{ item.image.url }} " class="card-img-top" alt="">

              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <div class="card-body text-center">
              <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                    <span class="badge badge-pill {{ item.get_label_display }}-color">{{item.get_types_display}}</span>
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong>$
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                </strong>
              </h4>

            </div>

          </div>

        </div>
        {% endfor %}
      </div>

    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->

    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item ">
          <a class="page-link" href="?page = {{ page_obj.previous_page_number}}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}


        <li class="page-item active">
          <a class="page-link" href="?page = {{ page_obj.number}}">{{ page_obj.number}}
            <span class="sr-only">(current)</span>
          </a>
        </li>
        
        {% if page_obj.has_next %}


        <li class="page-item">
          <a class="page-link" href="?page = {{ page_obj.next_page_number}}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}

      </ul>
    </nav>

    {% endif %}

  </div>
</main>

{% endblock content %}

templates/item_list.html
{{% extend "base.html" %}}


{% block content %}

<h2> Here is the list of the items</h2>

{% for item in items %}
{{ item }}

{% endfor %}

{% endblock content %}

templates/navbar.html
{% load cart_template_tags%}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="/">
      <strong class="blue-text">Happy Hours</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link waves-effect" href="/">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="/checkout">
            For Business</a>
        </li>

      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href=" {%  url 'core:order_summary' %}" class="nav-link waves-effect">
            <span class="badge red z-depth-1 mr-1"> {{ request.user | cart_item_count }}</span>
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href=" {% url 'account_logout' %}">

            <span class="clearfix d-none d-sm-inline-block"> Logout </span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href=" {% url 'account_login' %}">

            <span class="clearfix d-none d-sm-inline-block"> Login </span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link waves-effect" href=" {% url 'account_signup' %}">

            <span class="clearfix d-none d-sm-inline-block"> Signup </span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}


<main>
  <div class="container">
    <div class="table-responsive text-nowrap">
<h2>Order Summary</h2>
        <table class="table">
          <thead>
            <tr>
                              <th scope="col">#</th>

              <th scope="col">Item Title</th>
              <th scope="col">Price</th>
              <th scope="col">Quantity</th>
              <th scope="col">Total Item Price</th>
            </tr>
          </thead>
          <tbody>

          {% for order_item in object.items.all %}
            <tr>
              <th scope="row">1</th>
              <td>{{ order_item.item.title }}</td>
              <td>{{ order_item.item.price }}</td>
              <td>
                   <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>

                  {{ order_item.quantity }}


                  <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>

              </td>


                <td>{% if order_item.item.discount_price %}
                    {{ order_item.get_total_discount_item_price }}
                  <span class="badge badge-primary"> Saving ${{ order_item.get_amount_saved }} </span>
                  {% else %}
                  {{ order_item.get_total_item_price }}
                  {% endif %}

                <a href="{% url 'core:remove-from-cart' order_item.item.slug %}"><i class="fas fa-trash float-right"></i></a>
              </td>

            </tr>

             {% empty %}

              <tr>
              <td colspan="5"> Your Cart is Empty</td>
               <a class="btn btn-warning float-right ml-2 " href=" /">Continue Shopping</a>

              </tr>

          {% endfor %}
          {% if object.get_total %}
          <tr>
              <td colspan="4"><b>Order Total</b></td>
              <td><b>${{ object.get_total }}</b></td>
          </tr>
           <tr>
              <td colspan="5">
                  <a class="btn btn-primary float-right ml-2" href=" /checkout/">Proceed to checkout</a>
                  <a class="btn btn-warning float-right ml-2 " href=" /">Continue Shopping</a>

              </td>
          </tr>
          {% endif %}
          </tbody>
        </table>
      
      </div>
   
  </div>
</main>

{% endblock content %}

templates/product.html
{% extends "base.html" %}

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

                <img src="{{ item.image.url }} " class="card-img-top" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>


<label class="lead label">#TODO --> Reviews, Sizes</label> <br/>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
{#            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">#}
{#              Remove from cart#}
{#            </a>#}

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>


            <h4 class="my-4 h4">Product Details</h4>


          <table class="table">

  <tbody>
    <tr>
      <td>Category</td>
      <td>{{object.get_category_display}}</td>
    </tr>
    <tr>
      <td>Region</td>
      <td>#TODO </td>
    </tr>
    <tr>
      <td>Abv</td>
      <td>#TODO</td>
    </tr>
  <tr>
      <td>Features</td>
      <td>#TODO</td>
    </tr>
  <tr>
      <td>Food Pairing</td>
      <td>#TODO</td>
    </tr>
  </tbody>
</table>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->
  <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>
      <!--Grid row-->
      <div class="row wow fadeIn">


          <p class="lead font-weight-bold">Similar Products</p>
        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="{{ item.image }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://www.esewapasal.com/pub/media/catalog/product/cache/6157b2cd00c2efa35321a4f1cf89a568/1/6/16103.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://www.binnys.com/media/catalog/product/cache/eab16ae251e4410504af434c6d9419db/4/1/41657.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>

{% endblock content %}

templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>